In [2]:
import numpy as np

num_users = 4
num_items = 5

num_factors = 3

np.random.seed(0)
user_item_matrix = np.random.rand(num_users, num_items)

learning_rate = 0.01
num_epochs = 100
regularization = 0.1

user_matrix = np.random.rand(num_users, num_factors)
item_matrix = np.random.rand(num_items, num_factors)

for epoch in range(num_epochs):
    for i in range(num_users):
        for j in range(num_items):
            if user_item_matrix[i, j] > 0:
                prediction = np.dot(user_matrix[i, :], item_matrix[j, :])
                error = user_item_matrix[i, j] - prediction
                for k in range(num_factors):
                    user_matrix[i, k] += learning_rate * (2 * error * item_matrix[j, k] - 2 * regularization * user_matrix[i, k])
                    item_matrix[j, k] += learning_rate * (2 * error * user_matrix[i, k] - 2 * regularization * item_matrix[j, k])

predicted_matrix = np.dot(user_matrix, item_matrix.T)

print("Original User-Item Matrix:")
print(user_item_matrix)
print("\nPredicted User-Item Matrix:")
print(predicted_matrix)


Original User-Item Matrix:
[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]]

Predicted User-Item Matrix:
[[0.41141901 0.32376396 0.54669665 0.60737749 0.32140248]
 [0.4908066  0.39758452 0.72441999 0.77569144 0.44178481]
 [0.51765735 0.39648235 0.54915431 0.7066277  0.2768967 ]
 [0.33444655 0.28866723 0.60356497 0.60813243 0.3891929 ]]
